### ISSUE TITLE
outdated database

### ISSUE THREAD

**Issue by rcarsey1** [wiedehopf/tar1090-db#1]
It seems the files in the db folder are updated regularly.  However, my aircraft, N713 (A98731) has a type of "ULAC".  Additionally, I see that same information in the A9.js (gzipped) file if I run _get.sh_  on  my own machine.

This ICAO# shows up as "RV12" (correct) if I query the Mictronics website ([https://www.mictronics.de/aircraft-database/]) and is also correct in the mic-db.zip file that _get.sh_ downloads very early on.

The wackiness seems to start when _get.sh_  wgets the _basic-ac-db.json.gz_ from adsbexchange.com (all of this info is correct except for ULAC:

`{"icao":"a98731","reg":"N713","icaotype":"ULAC","year":"2020","manufacturer":"VANS AIRCRAFT INC","model":"RV-12IS","ownop":"CARSEY ROBERT A JR","faa_pia":false,"faa_ladd":false,"short_type":"L1P","mil":false}`

Not sure why they have wrong data.. but it seems later on in _get.sh_, some data may be combined and adsbexchange.com data is preferred (I haven't dug into toJson.py yet).  So I'm yet unsure at this time if the cause is my short N#, absdexchange.com having wrong/old info, or a bug.

According to Mictronics, they listed correct information in October 2020.

**Comment by wiedehopf** [comment]
It's being looked at.
