### ISSUE TITLE
Incorrect entries modification

### ISSUE THREAD

**Issue by VirusPilot** [wiedehopf/tar1090-db#11]
What is the process if database entries are incorrect and need to be modified? Is the database synchronized with other databases like airframes.org, ddb.glidernet.org, opensky?

**Comment by TLeconte** [comment]
Look at the script update.sh
It will give you the sources of database update

**Comment by VirusPilot** [comment]
Thank you for that hint but still I would like to know how to correct wrong entries in adsbexchange.

**Comment by VirusPilot** [comment]
In the meantime I found this one here: [https://www.adsbexchange.com/database/contribute/](url) but did not receive anything when requesting an "Admin Login". Now I joined the ADSBx Discord group and provided a change under # data-submission - let's see whether this works.

**Comment by VirusPilot** [comment]
ADSBx Discord group # data-submission worked, issue closed.
