### ISSUE TITLE
switching to Brotli compression

### ISSUE THREAD

**Issue by lart2150** [wiedehopf/tar1090-db#3]
What do you think about switching the compressed database from gzip to brotli?  regIcao.js is about 50% smaller when compressed with brotli then gzip.

https://caniuse.com/brotli

**Comment by wiedehopf** [comment]
I'll think about it.

How is old browser support?

**Comment by wiedehopf** [comment]
Oh nevermind, brotli only works with https, i knew there was a caveat.

**Comment by wiedehopf** [comment]
I've checked this possibility earlier and this was the reason i believe.

https://stackoverflow.com/questions/43862412/why-is-brotli-not-supported-on-http

**Comment by lart2150** [comment]
Well that's a bummer. I didn't know it only works with https.  _shakes fist at google_

**Comment by wiedehopf** [comment]
Yeah that's so stupid.
What's the issue with Accept-Encoding ... :(

I removed the no-transform again for adsbexchange global though so cloudflare can recompress with brotli.
